---
- hosts: tag_webserver
  remote_user: "user"
  become: "yes"
  vars:
    websiteheader: "Ansible Playbook Fantastico"
    websiteauthor: "SRE helped by script"

  roles:
  - jesperberth.el_httpd

  tasks:
  - name: Add index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root